name: 'Analyse codebase'

on:
  push:
    branches: [ main ]

concurrency:
  group: 'ktransport-analysis'
  cancel-in-progress: true

jobs:
  Analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'gradle'
      - name: Generate Test Coverage
        run: ./gradlew koverXmlReport
      - name: Uploading code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./ktransport/build/reports/kover/xml/report.xml,./ktransport-ksp/build/reports/kover/xml/report.xml,./example/build/reports/kover/xml/report.xml,./gradle-plugin/build/reports/kover/xml/report.xml
          fail_ci_if_error: true