name: 'Publish to Maven Central'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: 'ktransport-publish'
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: Publish library to maven central
        run: ./gradlew :ktransport:publish :ktransport-ksp:publish :grpc-common:publish :generate-proto:publish
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
      - name: Publish gradle plugin to GradlePluginPortal
        run: ./gradlew publishToGradlePluginPortal -Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{secrets.GRADLE_SECRET}}
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ github.ref_name }}